### ISSUE TITLE
Performance decreasement migrating from 3.0.3 to 4.8.0

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#249] opened 2020-03-05 15:21 UTC
<p>Hello,</p>

<p>I'm currently migrating a project, that uses Lucene.Net, from .Net Framework to .Net Core.</p>

<p>I had to migrate from 3.0.3 version of Lucene to 4.8.0 (beta0007) but I noticed performance decreasement while measuring response time while requesting the database. The response time using Lucene 4.8.0 is two to three times higher than 3.0.3 version.</p>

<p>I read some forum topics where other users noticed this performance decreasement too. Are you aware about that? Do you plan to do something to improve performances of Lucene 4.8.0?</p>

<p>Best regards</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-647">[LUCENENET-647]</a> created by Mo Dje</i>

**Comment by NightOwl888** [comment] 2020-08-24 21:37
Closing this because there is nothing here that can be reproduced and we have approximately doubled performance since this was reported.

**Closed by NightOwl888** 2020-08-24 21:37 UTC
