### ISSUE TITLE
Find all polygons containing the point 

### ISSUE THREAD

**Issue by yashhema** [apache/lucenenet#782] opened 2022-12-14 02:18 UTC
Hello,
I indexed MultiPolygon using this
       IDictionary<string, string> margs = new Dictionary<string, string>
            {
                ["SpatialContextFactory"] = typeof(NtsSpatialContextFactory).FullName
            };

        

            var ctx = SpatialContextFactory.MakeSpatialContext(margs, GetType().Assembly);
              SpatialPrefixTree trie = new QuadPrefixTree(ctx, 12);
            _locationfindstrategy = new TermQueryPrefixTreeStrategy(trie, "geo");

then indexed each polygon via
               IShape area = ctx.ReadShapeFromWkt(v.wktstr);
                Document doc = new Document();
                doc.Add(new TextField("id", v.stname, Field.Store.YES));
                Field[] fields = _locationfindstrategy.CreateIndexableFields(area, 0.025);
                foreach (Field field in fields)
                {
                    doc.Add(field);
                }

Now I am trying to search documents containing a point (For example , say i want to find the city from lat/long, and I have stored polygon shapes of city )

IPoint upperleft = ctx.MakePoint(92.515830993652514, 10.8976411819458);
            Query query = _locationfindstrategy.MakeQuery(new SpatialArgs(SpatialOperation.Contains, upperleft));

            TopDocs search = searcher.Search(query, 10);

I am getting error - Opeation Not supported

Is there any other mechanism which i can use

**Comment by NightOwl888** [comment] 2023-10-10 11:16
I am closing this because it is not a bug that needs addressing in Lucene.NET. Please direct usability questions to StackOverflow or the [Lucene.NET user mailing list](https://lucenenet.apache.org/contributing/index.html#ask-a-question). You will be much more likely to get an answer to your question on StackOverflow when specifying both `lucene.net` and `lucene` tags.

**Closed by NightOwl888** 2023-10-10 11:16 UTC
