### ISSUE TITLE
Cannot parse 'XX*': Encountered "<EOF>"

### ISSUE THREAD

**Issue by bbieniek** [apache/lucenenet#632] opened 2022-04-15 08:10 UTC
Hi,

We are right now on the following versions:
```
<PackageReference Include="Lucene.Net" Version="4.8.0-beta00016" />
<PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00016" />
```

Today, we have encountered a random error, that could not be reproduced:
```
Cannot parse 'Bl*': Encountered "<EOF>" at line 1, column 18.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
```

![image](https://user-images.githubusercontent.com/10694177/163543907-8a6ae858-23b3-430b-a622-b917935f9257.png)

We use MultiFieldQueryParser with two fields and the following call:
`Parse($"{input}*")`

What could be the cause of it?
The data is read from Azure Blob storage, using AzureDirectory package.

Thank you for your help.

**Comment by NightOwl888** [comment] 2022-04-15 15:46
What datatype is `{input}`?

I suspect you might be having parse issues due to the culture of the current thread in your application, which may be formatting `{input}` in an unexpected way. You may need to use [`FormattableString.Invariant()`](https://docs.microsoft.com/en-us/dotnet/api/system.formattablestring.invariant?view=net-6.0).

Note also that the parsing may be failing because a new `QueryParser` instance uses the culture of the current thread by default and you may need to change the culture.

```c#
var parser = new MultiFieldQueryParser(LuceneVersion.LUCENE_48, new string[] { "foo", "bar" }, analyzer)
{
    Locale = CultureInfo.InvariantCulture
};
```

Whatever the case, you should be able to debug what is happening by recording the culture and value to be parsed during a failure and then you should reproduce the issue in a debug environment so you can step through to debug. Note that you can [enable Source Link](https://lucenenet.apache.org/docs/4.8.0-beta00016/api/core/source-stepping.html) on 4.8.0-beta00016 so you can step into the QueryParser code also.

**Comment by bbieniek** [comment] 2022-04-15 15:50
It's a string.
The problem is that this happened just in one instance. I wasn't able to reproduce it when running the parsing on exactly the same string.

Thanks for the tip regarding Locale, I will try that and see if the error repeats

**Comment by bbieniek** [comment] 2022-04-21 07:36
After deploying the fix, it did not help.
Still getting the exception:
```
Cannot parse '"a"': Encountered "<EOF>" at line 1, column 2.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
```

One more thing, I am using the AzureDirectory package. I have noticed that this *may* occur when the cache is being downloaded from a blob container. I will ask the person that takes care of the Lucene.Net.Store.AzureDirectory package

**Comment by paulirwin** [comment] 2024-10-28 18:15
Thank you for your report, but I cannot reproduce with QueryParser or MultiFieldQueryParser and StandardAnalyzer, on either beta 16 or 17 (latest trunk). Closing this issue unless a reproducible case is provided.

**Closed by paulirwin** 2024-10-28 18:15 UTC

**Comment by Shazwazza** [comment] 2024-10-28 22:57
@paulirwin It occurs when accidentally using a `QueryParser` in a multi-threaded scenario. This is not a threadsafe API but this error will happen if you use one instance in several threads.

**Comment by paulirwin** [comment] 2024-10-28 23:07
@Shazwazza Great catch, thanks! I can now easily reproduce this failure even in Lucene 10.0 in Java by modifying my example to launch 100 threads that share a QueryParser. So this is not a Lucene.NET bug; the solution is to make sure that you are not sharing a QueryParser across threads.
