### ISSUE TITLE
Code snippets on https://lucenenet.apache.org/ doesn't works.

### ISSUE THREAD

**Issue by Kuinox** [apache/lucenenet#453] opened 2021-03-26 00:33 UTC
Hello,
I'm currently trying to get started on lucene.net, but no success so far.  
First small issue:  
The snippet on https://lucenenet.apache.org/ requires `Lucene.Net.Analysis.Common` which was not indicated.  
Second issue, if I simply copy/paste the first snippet, it throws me a `Lucene.Net.Index.IndexNotFoundException: 'no segments* file found in [truncated]`, on the IndexWriter constructor.

**Comment by NightOwl888** [comment] 2021-03-26 10:23
Thanks for letting us know about the issues you are having with the examples on the home page. We will surely look into finding ways to make the code that you see there runnable.

In the meantime, there are several runnable demos that you can inspect to get a feel for how the components work together to provide indexing and search:

## General Search

- [src/Lucene.Net.Demo/IndexFiles.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/IndexFiles.cs)
- [src/Lucene.Net.Demo/SearchFiles.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/SearchFiles.cs)
- [LuceneNetDemo](https://github.com/NightOwl888/LuceneNetDemo)

## Faceted Search

- [src/Lucene.Net.Demo/Facet/AssociationsFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/AssociationsFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/DistanceFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/DistanceFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/ExpressionAggregationFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/ExpressionAggregationFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/MultiCategoryListsFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/MultiCategoryListsFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/RangeFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/RangeFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/SimpleFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/SimpleFacetsExample.cs)
- [src/Lucene.Net.Demo/Facet/SimpleSortedSetFacetsExample.cs](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/Facet/SimpleSortedSetFacetsExample.cs)

## Runnable Demos

Do note that all of the above examples from `Lucene.Net.Demo` are compiled into the [`lucene-cli` tool](https://lucenenet.apache.org/docs/4.8.0-beta00013/cli/demo/index.html) where they can be run if you don't happen to have handy access to an IDE. The code can also be viewed on the console and output to your local file system.

**Comment by Kuinox** [comment] 2021-03-26 13:27
I tried to run the cli to see if the issue is not specific to my PC, but it look like the CLI need configuration after install and the doc doesn't specify it:  
```
PS C:\Users\Kuinox> lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\Kuinox\.dotnet\tools\.store\lucene-cli\4.8.0-beta00013\lucene-cli\4.8.0-beta00013\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27
```
So I found out that, the demo is working, but I was catching every exception and never let it run to completion ><.

**Comment by NightOwl888** [comment] 2021-03-26 16:46
Thanks for the additional report. I have confirmed the behavior and discovered this has been failing since 4.8.0-beta00009.

```
F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00013
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00013') was successfully installed.

F:\Projects\lucenenet>lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\shad\.dotnet\tools\.store\lucene-cli\4.8.0-beta00013\lucene-cli\4.8.0-beta00013\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27

F:\Projects\lucenenet>dotnet tool uninstall lucene-cli -g
Tool 'lucene-cli' (version '4.8.0-beta00013') was successfully uninstalled.

F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00012
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00012') was successfully installed.

F:\Projects\lucenenet>lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\shad\.dotnet\tools\.store\lucene-cli\4.8.0-beta00012\lucene-cli\4.8.0-beta00012\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27

F:\Projects\lucenenet>dotnet tool uninstall lucene-cli -g
Tool 'lucene-cli' (version '4.8.0-beta00012') was successfully uninstalled.

F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00011
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00011') was successfully installed.

F:\Projects\lucenenet>lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\shad\.dotnet\tools\.store\lucene-cli\4.8.0-beta00011\lucene-cli\4.8.0-beta00011\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27

F:\Projects\lucenenet>
F:\Projects\lucenenet>dotnet tool uninstall lucene-cli -g
Tool 'lucene-cli' (version '4.8.0-beta00011') was successfully uninstalled.

F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00010
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00010') was successfully installed.

F:\Projects\lucenenet>lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\shad\.dotnet\tools\.store\lucene-cli\4.8.0-beta00010\lucene-cli\4.8.0-beta00010\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27

F:\Projects\lucenenet>dotnet tool uninstall lucene-cli -g
Tool 'lucene-cli' (version '4.8.0-beta00010') was successfully uninstalled.

F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00009
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00009') was successfully installed.

F:\Projects\lucenenet>lucene
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\shad\.dotnet\tools\.store\lucene-cli\4.8.0-beta00009\lucene-cli\4.8.0-beta00009\tools\netcoreapp3.1\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lucene.Net.Cli.Program.Main(String[] args) in D:\a\1\s\src\dotnet\tools\lucene-cli\Program.cs:line 27

F:\Projects\lucenenet>dotnet tool uninstall lucene-cli -g
Tool 'lucene-cli' (version '4.8.0-beta00009') was successfully uninstalled.

F:\Projects\lucenenet>dotnet tool install lucene-cli -g --version 4.8.0-beta00008
You can invoke the tool using the following command: lucene
Tool 'lucene-cli' (version '4.8.0-beta00008') was successfully installed.

F:\Projects\lucenenet>lucene
 Lucene.Net Command Line Utility, Version: 4.8.0-beta00008 commit:[c63b8834c6]

Usage:  [command]

Commands:
  analysis   Utilities to manage specialized analyzers.
  benchmark  Utilities for benchmarking Lucene.Net.
  demo       Demos for various Lucene.Net functionality including C# code samples.
  index      Utilities to analyze or maintain an index.
  lock       Utilities for verifying concurrent locking integrity.

Use " [command] --help" for more information about a command.


F:\Projects\lucenenet>
```

It seems that when the `Microsoft.Extensions.Configuration` features were added, the default option of requiring an `appsettings.json` file was chosen instead of allowing it to be optional.

I am considering just supplying a `appsettings.json` file with all of the default settings to make it clearer which settings are available in `lucene-cli` until we have documentation (see #307). But even with a default file, it should still be made optional.

In addition, it is clear we need some basic smoke tests to ensure that the tool will install and run without throwing exceptions.

In the meantime, you can work around this problem by manually adding an empty JSON file named `appsettings.json` to the appropriate directory on your system. 

#### appsettings.json
```json
{
}
```

> **IMPORTANT**: There must be at least opening and closing curly brackets in the file, or it won't be parsed as valid JSON.

The location it is looking for the file on your system in is in the error message:

```
The physical path is 'C:\Users\Kuinox\.dotnet\tools\.store\lucene-cli\4.8.0-beta00013\lucene-cli\4.8.0-beta00013\tools\netcoreapp3.1\any\appsettings.json'.
```

But if you need more help locating where the tool is located, see [How to manage .NET tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).

**Comment by Kuinox** [comment] 2021-03-26 17:00
I was running the tool only to know if LuceneNet could run on my machine :p.

Is it expected that Lucene.Net throws exceptions internally (but catches them) in normal operations?

**Comment by NightOwl888** [comment] 2021-03-26 17:06
> I was running the tool only to know if LuceneNet could run on my machine :p.
>
> Is it expected that Lucene.Net throws exceptions internally (but catches them) in normal operations?

This is a line-by-line port of Java Lucene. The designers made the unfortunate choice to rely on exceptions for control flow by using exceptions as messages similar to events. This behavior was deemed too much of a risk to change due to the fact that some bugs can only be found by comparing where the execution paths diverge between Lucene and Lucene.NET.

**Comment by NightOwl888** [comment] 2021-04-15 20:55
Closing as #453 fixes the `appsettings.json` problem and #457 is tracking the hope page code sample issue.

**Closed by NightOwl888** 2021-04-15 20:55 UTC
Labels: is:bug, pri:high
