### ISSUE TITLE
Random Query Parser Error

### ISSUE THREAD

**Issue by danlb2000** [apache/lucenenet#888] opened 2023-11-20 22:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are using Umbraco 10.6.1 which uses Examine 3.0.1.0 and Lucene.net 4.8.0.0. Periodically we get the error shown below when trying to query an index. Once this error starts occurring it occurs for every search until we restart the ASP.NET app pool at which point the queries start working fine again. When this error is occurring, queries that once worked fine, now fail. Someone posted about an identical error on the Examine github page but the developers there sent us here. 

System.NullReferenceException: Object reference not set to an instance of an object.
at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_add_error_token(Int32 kind, Int32 pos)
at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_scan_token(Int32 kind)
at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_3R_2()
at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_3_1()
at Lucene.Net.QueryParsers.Classic.QueryParser.Jj_2_1(Int32 xla)
at Lucene.Net.QueryParsers.Classic.QueryParser.Clause(String field)
at Lucene.Net.QueryParsers.Classic.QueryParser.Query(String field)
at Lucene.Net.QueryParsers.Classic.QueryParser.TopLevelQuery(String field)
at Lucene.Net.QueryParsers.Classic.QueryParserBase.Parse(String query)
at Examine.Lucene.Search.LuceneSearchQueryBase.GetFieldInternalQuery(String fieldName, IExamineValue fieldValue, Boolean useQueryParser)
at Examine.Lucene.Search.LuceneSearchQuery.Search(QueryOptions options)

### Steps To Reproduce

Unfortunately we have not figured out how to reproduce the error, it just seems to happen randomly. Once it occurs, it continues to error until we restart the app pool. 

### Lucene.NET Version

4.8.0.0. 

### .NET Version

.net Core 6.0

### Operating System

Windows 

### Anything else?

ASP.NET

**Comment by NightOwl888** [comment] 2024-01-19 18:54
I am closing because there is no info provided about how to reproduce the issue.

It looks like Examine has provided an update to resolve the issue: https://github.com/Shazwazza/Examine/issues/335.

**Closed by NightOwl888** 2024-01-19 18:54 UTC
Labels: is:bug
